FROM ubuntu:18.04

RUN apt update -y
RUN apt install gcc -y
RUN apt install g++ -y
RUN apt install cmake -y
RUN apt install pkg-config -y
RUN apt install libunwind-dev -y
RUN apt install llvm-10-dev -y
RUN apt install libclang-10-dev -y
RUN apt install libncurses-dev -y
RUN apt install libboost-system-dev libboost-filesystem-dev -y
RUN apt install libctemplate-dev -y
RUN apt install libdw-dev -y

