#ifndef EASYMOCK_CPPCONSTREFINTFUNCONSTREFINT_H
#define EASYMOCK_CPPCONSTREFINTFUNCONSTREFINT_H

const int& cppConstRefIntFunConstRefInt(const int& a);

#endif //EASYMOCK_CPPCONSTREFINTFUNCONSTREFINT_H
