#ifndef EASYMOCK_CPPCLASSVOIDFUNVOIDCONST_H
#define EASYMOCK_CPPCLASSVOIDFUNVOIDCONST_H

class ClassVoidFunVoidConst
{
public:
  void voidFunVoidConst() const;
};

#endif //EASYMOCK_CPPCLASSVOIDFUNVOIDCONST_H
