name: Linux Ubuntu 20.04 arm64 GCC

on: [push, pull_request]

jobs:
  ubuntu-20-04-arm-gcc:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        build_type: [Debug, ReleaseWithTest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate
        uses: ./.github/actions/validate-arm64
        with:
          c_compiler: gcc
          cxx_compiler: g++
          build_type: ${{ matrix.build_type}}
          docker_image: ubuntu:20.04
