name: Linux Ubuntu 18.04 arm64 GCC

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      tmate_enabled:
        description: 'Run the build with tmate debugging session enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        type: boolean
        default: false

jobs:
  ubuntu-18-04-arm-gcc:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        build_type: [Debug, ReleaseWithTest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate
        uses: ./.github/actions/validate-arm64
        with:
          c_compiler: gcc
          cxx_compiler: g++
          build_type: ${{ matrix.build_type }}
          docker_image: ubuntu:18.04
