name: MacOS 10.15 Clang

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      tmate_enabled:
        description: 'Run the build with tmate debugging session enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        type: boolean
        default: false

jobs:
  macos-10-15-clang:
    runs-on: macos-10.15
    strategy:
      matrix:
        # Debug isn't yet tested because it failed with ASAN
        # The first analysis is that it is a bug in ASAN itself
        build_type: [Debug, ReleaseWithTest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate
        uses: ./.github/actions/validate-native
        with:
          c_compiler: clang
          cxx_compiler: clang++
          build_type: ${{ matrix.build_type }}
