name: Linux Ubuntu 18.04 x86 Clang

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      tmate_enabled:
        description: 'Run the build with tmate debugging session enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        type: boolean
        default: false

jobs:
  ubuntu-18-04-x86-clang:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        build_type: [Debug, ReleaseWithTest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate
        uses: ./.github/actions/validate-native
        with:
          c_compiler: clang-8
          cxx_compiler: clang++-8
          build_type: ${{ matrix.build_type }}
