name: Linux Ubuntu 24.04 x86 GCC

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      tmate_enabled:
        description: 'Run the build with tmate debugging session enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        type: boolean
        default: false

jobs:
  ubuntu-24-04-x86-gcc:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        build_type: [Debug, ReleaseWithTest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate
        uses: ./.github/actions/validate-native
        with:
          c_compiler: gcc
          cxx_compiler: g++
          build_type: ${{ matrix.build_type }}
