name: Linux Ubuntu 20.04 x86 Clang

on: [push, pull_request]

jobs:
  ubuntu-20-04-x86-clang:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        build_type: [Debug, ReleaseWithTest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate
        uses: ./.github/actions/validate-native
        with:
          c_compiler: clang
          cxx_compiler: clang++
          build_type: ${{ matrix.build_type}}
