name: Validate simple FIFO driver

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      tmate_enabled:
        description: 'Run the build with tmate debugging session enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        type: boolean
        default: false

jobs:
  ubuntu-20-04-x86-gcc:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |-
          sudo apt update -y
          sudo apt install \
            gcc \
            g++ \
            cmake \
            pkg-config \
            libunwind-dev \
            llvm-12-dev \
            libclang-12-dev \
            libclang-cpp12-dev \
            libncurses-dev \
            libboost-system-dev \
            libboost-filesystem-dev \
            libctemplate-dev \
            libdw-dev \
            doxygen \
            graphviz

      - name: Pull and prepare simple FIFO driver repo
        run: |-
          git clone https://github.com/lcarlier/simpleFifoKernelDriver.git /tmp/simpleFifoKernelDriver
          rm -rf /tmp/simpleFifoKernelDriver/extern/EasyMock
          ln -s `pwd` /tmp/simpleFifoKernelDriver/extern/EasyMock

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session if enabled
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tmate_enabled == 'true' }}

      - name: Run test
        run: |-
          cd /tmp/simpleFifoKernelDriver/
          cmake -B build
          cd build
          make -j `nproc` all
          ctest --output-on-failure

      - name: Store artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: |
            /tmp/simpleFifoKernelDriver/**/*.c
            /tmp/simpleFifoKernelDriver/**/*.cpp
            /tmp/simpleFifoKernelDriver/**/*.h
            /tmp/simpleFifoKernelDriver/**/*.hpp
            /tmp/simpleFifoKernelDriver/**/*.txt
            /tmp/simpleFifoKernelDriver/**/Kbuild
